### ISSUE TITLE
Compile from source question

### ISSUE THREAD

**Issue by harrihaven2** [BishopFox/sliver#174] opened 2020-04-15 19:09 UTC
## Hey there!

This is a super cool project, and I really appreciate the work you're putting into it! I am trying to compile from source as per the instructions on the wiki, but I've not familiar with Golang and I'm hitting a snag. I'm not sure how to install the proto* packages correctly. 

### Here is my error when I try to generate an obfuscated payload on sliver:

Compiling, please wait .../home/dev/.sliver/slivers/windows/386/UPSET_GLOCKENSPIEL/obfuscated/src/github.com/bishopfox/sliver/protobuf/sliver/constants.go:11:15: could not import google.golang.org/protobuf/reflect/protoreflect (cannot find package "google.golang.org/protobuf/reflect/protoreflect" in any of:
	/home/dev/.sliver/go/src/google.golang.org/protobuf/reflect/protoreflect (from $GOROOT)
	/home/dev/.sliver/slivers/windows/386/UPSET_GLOCKENSPIEL/obfuscated/src/google.golang.org/protobuf/reflect/protoreflect (from $GOPATH))
/home/dev/.sliver/slivers/windows/386/UPSET_GLOCKENSPIEL/obfuscated/src/github.com/bishopfox/sliver/protobuf/sliver/constants.go:12:12: could not import google.golang.org/protobuf/runtime/protoimpl (cannot find package "google.golang.org/protobuf/runtime/protoimpl" in any of:
	/home/dev/.sliver/go/src/google.golang.org/protobuf/runtime/protoimpl (from $GOROOT)
	/home/dev/.sliver/slivers/windows/386/UPSET_GLOCKENSPIEL/obfuscated/src/google.golang.org/protobuf/runtime/protoimpl (from $GOPATH))
/home/dev/.sliver/slivers/windows/386/UPSET_GLOCKENSPIEL/obfuscated/src/github.com/bishopfox/sliver/protobuf/sliver/constants.go:26:17: ProtoPackageIsVersion4 not declared by package proto
[*] Build completed in 00:00:01
[!] Build failed, no file data

###This is what I've tried:
- Installing protoc, protoc-gen-go, and packr in my $GOPATH which is different than my $GOROOT.
- Extracting the Protobuf 3.7 package into my $GOROOT

### Conclusion and System Details
I know it is an error with how I'm installing those proto* packages but I don't know how to fix it.
I'm on a non-root account in Kali Linux 2020.1.

**Comment by moloch--** [comment] 2020-04-15 20:33
Looks like a duplicate of issue #172 --we're looking into it, looks like one of our dependencies had a breaking change.

**Comment by moloch--** [comment] 2020-04-15 21:57
Fixed please see issue #172 for details.

**Closed by moloch--** 2020-04-15 21:57 UTC
Labels: bug, duplicate

**Comment by harrihaven2** [comment] 2020-04-16 12:09
Thanks! That makes me feel a bit more validated after spending several hours trying everything I could think of. :P)

**Comment by harrihaven2** [comment] 2020-04-16 17:10
After clearing out the old installation and following the new wiki directions, I'm still running into an issue where ./sliver-server will return immediately after I run it. Should I open a new issue?

**Comment by moloch--** [comment] 2020-04-16 19:03
Double check to make sure you don't have another instance of `sliver-server` running, that's usually due to the database failing to lock the files needed to start (I need to add a verbose error when this occurs). Check the logs to be sure.

**Comment by harrihaven2** [comment] 2020-04-17 13:29
Ah, that would explain it! Thank you. 

However, when I try to generate a payload it still outputs the same error as in my original post and #172 . I have repeatedly cleared out my GOPATH and go/src/github.com/bishopfox/sliver and followed the new Compile From Source instructions closely, but I get the same result each time. 

In the error it seems to reference my GOPATH as "/home/dev/.sliver/slivers/windows/386/UPSET_GLOCKENSPIEL/obfuscated/src/google.golang.org/protobuf/reflect/protoreflect (from $GOPATH))" but my actual GOPATH is much different. I don't know enough about golang to know if that's irrelevant or not. 

What information should I include that would be helpful?

**Comment by moloch--** [comment] 2020-04-17 13:49
Make sure you don't have v1.4.0 of `protoc-gen-go` on your OS `$PATH` (not just your `$GOPATH`). After than run `make clean-all` and `./go-assets.sh` before rerunning `make`.

**Comment by harrihaven2** [comment] 2020-04-17 14:19
Ah! That was it! Thank you so much :+1:

**Comment by moloch--** [comment] 2020-04-17 14:27
I also added a verbose error for failed database file locks in https://github.com/BishopFox/sliver/commit/3c20b12fab7de354be6bbd8a99e9590e7d736e7c
