### ISSUE TITLE
generate error

### ISSUE THREAD

**Issue by WHOLETTHEDOG-OUT** [BishopFox/sliver#1054] opened 2023-01-04 06:17 UTC
![image](https://user-images.githubusercontent.com/13184758/210531241-29d994d0-ec9b-4528-987f-ee1c908014c9.png)

**Comment by WHOLETTHEDOG-OUT** [comment] 2023-01-04 07:03
![image](https://user-images.githubusercontent.com/13184758/210501341-929d874c-6773-47c7-ae6a-a12ee8ee416a.png)

**Comment by necroph0s** [comment] 2023-01-04 08:31
I suppose I'm to blame, I'll work on this in the AM.

**Comment by moloch--** [comment] 2023-01-04 16:22
Duplicate of #1055

**Closed by moloch--** 2023-01-04 16:22 UTC
Labels: bug, duplicate
