### ISSUE TITLE
Client side system/shell command execution feature

### ISSUE THREAD

**Issue by bryanmcnulty** [BishopFox/sliver#1394] opened 2023-08-27 16:32 UTC
It would be quite useful to have a way of executing system commands from the client (on the client side of course). Something like `!<CMD>` or `system <CMD>`. This way if one needed to read a local file on the client host, they could run `!cat note.txt` (Linux) or `!type note.txt` (Windows) instead of having to use a separate shell session

**Comment by rkervella** [comment] 2023-08-28 00:55
Duplicate of #124 , still not sure whether we'd want that or not

**Comment by maxlandon** [comment] 2023-08-29 10:48
Probably needed if the most recent work on the client is to be merged.

You'll have access to your shell any way you want without compromise.

**Closed** 2024-05-17 11:21 UTC
Labels: duplicate
