### ISSUE TITLE
Manually setting the HTTP-Host-Header

### ISSUE THREAD

**Issue by 0x646f6d** [BishopFox/sliver#328] opened 2021-02-03 21:30 UTC
I would like to use sliver in a Domain Fronting scenario. It doesn't seem possible currently as I cannot set the HTTP-Host-Header. Is there any work in progress?

**Comment by moloch--** [comment] 2021-02-03 21:49
Correct, domain fronting is another unsupported technique right now. However, the code is of course open source!

**Comment by moloch--** [comment] 2021-02-03 21:51
Duplicate of https://github.com/BishopFox/sliver/issues/140 going to close this one.

**Closed by moloch--** 2021-02-03 21:51 UTC
Labels: duplicate, enhancement
