### ISSUE TITLE
Sliver rpc error: code = Unknown desc = exit status 1

### ISSUE THREAD

**Issue by njahrckstr** [BishopFox/sliver#949] opened 2022-10-17 17:59 UTC
Setting up a new AWS instance to use Sliver and continue getting the following error:

`[server] sliver > generate --mtls <IP removed> --save /var/www/html --arch arm64 --os mac`

`[*] Generating new darwin/arm64 implant binary
[*] Symbol obfuscation is enabled
[!] rpc error: code = Unknown desc = exit status 1`

I'm using an AWS image of Kali:
`Linux kali 5.19.0-kali2-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1kali2 (2022-10-10) x86_64 GNU/Linux`
`# cat /etc/*release
ID="ec2"
VERSION="202208170508"
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.3"
VERSION_ID="2022.3"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"`

I'm wondering if this is a kernel issue...?

It works just fine on my other 2022.3 Kali instance running 5.18

**Comment by njahrckstr** [comment] 2022-10-17 19:13
These are the only errors from the log:

![Screen Shot 2022-10-17 at 3 13 15 PM](https://user-images.githubusercontent.com/41128138/196262637-bcb84791-a475-4471-8ad5-e5f0a98d4959.png)


As for the binary, I haven't been able to generate it due to the error

**Comment by rkervella** [comment] 2022-10-17 19:16
What version of slive are you running? Did you upgrade from a previous version?

**Comment by njahrckstr** [comment] 2022-10-17 19:17
![Screen Shot 2022-10-17 at 3 17 19 PM](https://user-images.githubusercontent.com/41128138/196263428-12a549df-38e0-436a-b725-ecf377407457.png)

**Comment by moloch--** [comment] 2022-10-17 19:19
Does this occur every time you run the `generate` command or is it intermittent?

**Comment by moloch--** [comment] 2022-10-17 19:20
@rkervella looks like it could be an issue with garble/krb5 library maybe?

**Comment by rkervella** [comment] 2022-10-17 19:20
The issue is likely related to the Kerberos SSH PR we merged a few weeks ago. I had this issue when garble was out of date, hence why I'm asking whether the server has been updated recently (and garble might be too old).

**Comment by moloch--** [comment] 2022-10-17 19:21
@njahrckstr did you compile this yourself or download a release?

**Comment by njahrckstr** [comment] 2022-10-17 19:23
I downloaded it via Kali package manager

**Comment by rkervella** [comment] 2022-10-17 19:24
Ah yeah I would avoid doing that. We're not the ones packaging Sliver for kali.

**Comment by njahrckstr** [comment] 2022-10-17 19:25
ok will do...

**Comment by moloch--** [comment] 2022-10-17 19:26
Be sure to run this command too: `sliver-server unpack --force`

**Comment by njahrckstr** [comment] 2022-10-17 19:31
Ah looks like that was the issue. :) Thanks for the help.

**Closed** 2022-10-17 19:32 UTC
Labels: investigating

**Comment by moloch--** [comment] 2022-10-17 19:50
Upstream bug report https://gitlab.com/kalilinux/packages/sliver/-/issues/2

**Comment by coderMohammed1** [comment] 2026-01-29 05:03
same issue on WSL
