### ISSUE TITLE
Invalid format

### ISSUE THREAD

**Issue by demonsec666** [BishopFox/sliver#118] opened 2019-08-08 05:36 UTC
![image](https://user-images.githubusercontent.com/24873495/62677576-6da7bb80-b9e1-11e9-833a-8080b2947a78.png)

**Comment by rkervella** [comment] 2019-08-08 06:46
We're going to need more details about that. Please use the issue template.

**Comment by rkervella** [comment] 2019-10-17 07:44
Can't reproduce without details. I'm closing this one.

**Closed by rkervella** 2019-10-17 07:44 UTC
Labels: bug
