### ISSUE TITLE
Aliases have problem with whitespace in arguments

### ISSUE THREAD

**Issue by jamesgol** [BishopFox/sliver#953] opened 2022-10-18 18:14 UTC
**Describe the bug**
Aliases have an issue with quoted whitespace.  I know [the wiki](https://github.com/BishopFox/sliver/wiki/Aliases-&-Extensions#aliases-command-parsing) says things should be escaped properly. 

I'm not sure what the best option is:
* Change parser should preserve quotes (probably asking for trouble)
* client/command/alias/load.go->runAliasCommand() should quote all args (or maybe just ones with whitespace)
* Update the docs/examples to show proper usage

This works, note the escaping around the -a arg
` sharpersist -- -t startupfolder -c "C:\Windows\System32\cmd.exe" -a \"/c calc.exe\" -f "SomeFileName" -m add`

I'm going to see about adding debug output of the command being executed on the server and the implant, I had to attach a debugger to figure this one out.

**Comment by moloch--** [comment] 2022-10-18 18:19
We're still using a fork of grumble so we could make this change, however we'd need to maintain the fork of grumble going forward, which i'm not sure we really want to be doing.

**Comment by rkervella** [comment] 2022-10-18 18:20
You can also use single quotes (avoids you to escape the quotes):

```
sharpersist -- -t startupfolder -c "C:\Windows\System32\cmd.exe" -a '"/c calc.exe"' -f "SomeFileName" -m add
```

I'd opt for a few more examples in the docs, instead of forking grumble and "auto-escaping" stuff.

**Comment by rkervella** [comment] 2022-10-18 18:22
Marking as duplicate of #944 since it's basically the same issue

**Comment by jamesgol** [comment] 2022-10-18 18:23
I've worked on cli stuff that had some crazy auto-escaping, definitely prefer to avoid that.  I think adding to the docs (this issue even helps because someone might find it in a search).    The extra debug output displaying what's actually executing would go a long way in tracking down issues too.

**Comment by rkervella** [comment] 2022-10-18 18:24
IIRC we do that for the `sideload`, `execute-assembly` and `spawndll` commands, just forgot to add it to aliases.

**Closed** 2022-10-18 19:53 UTC
Labels: duplicate, UX
