### ISSUE TITLE
armory segmentation fault

### ISSUE THREAD

**Issue by rootpentesting** [BishopFox/sliver#1614] opened 2024-03-26 11:55 UTC
![afbeelding](https://github.com/BishopFox/sliver/assets/68161162/8faf7e7b-6855-416c-9d12-59fe2a8885a4)

i am getting this error when trying to use armory, is there a way to uninstall sliver/ and reinstall ? 
it worked before installing the net-tools. it looks like a package got corrupted during installation. 

Text output : 

sliver > armory

[*] Fetching 1 armory index(es) ... done!
[*] Fetching package information ... panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9d86a6]

goroutine 181 [running]:
github.com/bishopfox/sliver/client/command/armory.downloadRequest({0x0, 0x0, 0x0, 0xd18c2e2800, 0x0}, {0xc000d87180, 0x69}, 0xc00061dcb0?)
        github.com/bishopfox/sliver/client/command/armory/parsers.go:439 +0x166
github.com/bishopfox/sliver/client/command/armory.GithubArmoryPackageParser(0x1587a80?, 0xc00061eaf0, 0x1, {0x0, 0x0, 0x0, 0xd18c2e2800, 0x0})
        github.com/bishopfox/sliver/client/command/armory/parsers.go:318 +0x325
github.com/bishopfox/sliver/client/command/armory.fetchPackageSignature(0xc00050db30?, 0x26d9480, 0xc00061eaf0, {0x0, 0x0, 0x0, 0xd18c2e2800, 0x0})
        github.com/bishopfox/sliver/client/command/armory/armory.go:487 +0x410
created by github.com/bishopfox/sliver/client/command/armory.fetchPackageSignatures
        github.com/bishopfox/sliver/client/command/armory/armory.go:445 +0x113

**Comment by rkervella** [comment] 2024-03-26 20:36
Duplicate of #1401

**Closed by rkervella** 2024-03-26 20:36 UTC
Labels: duplicate
