### ISSUE TITLE
Build failed on generate for darwin with obfuscation enabled

### ISSUE THREAD

**Issue by rkervella** [BishopFox/sliver#112] opened 2019-07-05 13:49 UTC
**Describe the bug**
Compilation fails when platform is darwin and obfuscation is enabled. Using `--debug` or `--skip-symbols` does work.

**To Reproduce**
1. Start sliver-server
2. Run `generate --os darwin --mtls 127.0.0.1:8888`
3. See error

**Expected behavior**
Sliver compilation should succeed

**Screenshots**
Output from sliver-server:
```
sliver > generate --os darwin --mtls 172.16.10.10:8888

[*] Generating new darwin/amd64 Sliver binary
[*] Symbol obfuscation is enabled, this process takes about 15 minutes
 ⠧  Compiling, please wait .../home/lesnuages/.sliver/go/src/net/cgo_bsd.go:15:72: could not determine kind of name for C.AI_MASK
gcc: error: unrecognized command line option '-mmacosx-version-min=10.10'
cgo failed: [go tool cgo -objdir /tmp/crypto_x509_C053128628 -- -I /tmp/crypto_x509_C053128628 -mmacosx-version-min=10.10 -D__MAC
_OS_X_VERSION_MAX_ALLOWED=101300 root_cgo_darwin.go]: exit status 1
 ⠇  Compiling, please wait ...cgo failed: [go tool cgo -objdir /tmp/net_C605240681 -- -I /tmp/net_C605240681 cgo_bsd.go cgo_resne
w.go cgo_sockold.go cgo_unix.go]: exit status 1
[*] Build completed in 00:00:01
[!] Build failed, no file data
```
Log files:

```
INFO[0014] [sliver/server/gobfuscate/main.go:59] Obfuscating strings ... 
INFO[0014] [sliver/server/gobfuscate/main.go:66] Obfuscating package names ... 
ERRO[0014] [sliver/server/gobfuscate/main.go:68] Failed to obfuscate package names: package move: couldn't load packages due to errors: net, crypto/x509 
INFO[0014] [sliver/server/generate/binaries.go:474] Error while obfuscating sliver package move: couldn't load packages due to errors: net, crypto/x509
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Version sliver-server v0.0.7

**Comment by moloch--** [comment] 2019-07-05 14:45
Clearly something to do with the interactions with the cross-compiler ... I've not come across this before though.

**Comment by rkervella** [comment] 2019-07-05 15:30
Here's the `gcc --version`:

```
gcc --version
gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by capnspacehook** [comment] 2019-07-05 16:30
Darwin implants always require CGO?

**Comment by moloch--** [comment] 2019-07-05 17:30
No they shouldn't, not sure why this is coming up unless you're trying to compile a SharedLib or something?

**Comment by moloch--** [comment] 2019-07-07 17:51
I think the issue is that the `gobfuscate` package is calling `go tool` somewhere under the hood with CGO enabled, which is annoying af because we specifically disable CGO in this type of build.

**Comment by moloch--** [comment] 2020-02-01 18:12
Fixed in `master` https://github.com/BishopFox/sliver/commit/d1b66e1da0748735f609a8902e31d3bfb7dcd422

**Closed by moloch--** 2020-02-01 18:12 UTC
Labels: bug
