### ISSUE TITLE
Q: Reuse beacon generated from a different sliver server

### ISSUE THREAD

**Issue by xinhuang** [BishopFox/sliver#1254] opened 2023-05-30 01:53 UTC
**Describe the bug**
The beacon generated on host A cannot connect to sliver server on host B.

**To Reproduce**
1. Host A: `generate beacon -S 5 -k -1 -b https://<Host B IP>:443 -s beacon -o linux -d`
2. Run `beacon`

**Expected behavior**
Expect the generated beacon from Host A to connect to Host B.

**Screenshots**
```
2023/05/30 10:46:44 sliver.go:97: Hello my name is DISASTROUS_POLICEMAN
2023/05/30 10:46:44 limits.go:58: Limit checks completed
2023/05/30 10:46:44 sliver.go:114: Running in Beacon mode with ID: 6967e199-61fc-4776-80d0-346a2322cf5d
2023/05/30 10:46:44 beacon.go:101: Starting beacon loop ...
2023/05/30 10:46:44 transports.go:41: Starting c2 url generator () ...
2023/05/30 10:46:44 transports.go:104: Return generator: (chan *url.URL)(0xc00009c720)
2023/05/30 10:46:44 beacon.go:117: Recv from c2 generator ...
2023/05/30 10:46:44 transports.go:92: Yield c2 uri = 'https://10.10.16.6:443'
2023/05/30 10:46:44 transports.go:92: Yield c2 uri = 'https://10.10.16.6:443'
2023/05/30 10:46:44 beacon.go:121: Next CC = https://10.10.16.6:443
2023/05/30 10:46:44 beacon.go:167: Beaconing -> https://10.10.16.6:443
2023/05/30 10:46:44 beacon.go:121: Next CC = https://10.10.16.6:443
2023/05/30 10:46:44 beacon.go:167: Beaconing -> https://10.10.16.6:443
2023/05/30 10:46:44 transports.go:92: Yield c2 uri = 'https://10.10.16.6:443'
2023/05/30 10:46:44 sliver.go:123: Next beacon = &{0xa7fe40 0xa844c0 0xa7fd00 0xa7fd80 0xa84500 0xa7fca0 https://10.10.16.6:443 }
2023/05/30 10:46:44 httpclient.go:668: [http] segments = [namespaces oauth2], filename = samples, ext = php
2023/05/30 10:46:44 crypto.go:189: TOTP Code (2023-05-30 01:46:44.110172464 +0000 UTC): 91733279
2023/05/30 10:46:44 httpclient.go:339: [http] POST -> https://10.10.16.6:443/namespaces/oauth2/samples.html?j=16033579&qt=91733a279 (106 bytes)
2023/05/30 10:46:44 httpclient.go:360: [http] non-200 response (404): &{404 Not Found 404 HTTP/1.1 1 1 map[Content-Length:[0] Date:[Tue, 30 May 2023 01:46:44 GMT]] 0xc000376180 0 [] false false map[] 0xc000378200 0xc0000c68f0}
2023/05/30 10:46:44 httpclient.go:668: [http] segments = [api api oauth php db oauth2], filename = api, ext = php
2023/05/30 10:46:44 crypto.go:189: TOTP Code (2023-05-30 01:46:44.000198818 +0000 UTC): 91733279
2023/05/30 10:46:44 httpclient.go:339: [http] POST -> http://10.10.16.6:80/api/api/oauth/php/db/oauth2/api.html?i=51632847&pq=917r33279 (106 bytes)
2023/05/30 10:46:44 httpclient.go:360: [http] non-200 response (404): &{404 Not Found 404 HTTP/1.1 1 1 map[Content-Length:[0] Date:[Tue, 30 May 2023 01:46:44 GMT]] 0xc0003762e0 0 [] false false map[] 0xc000378600 <nil>}
2023/05/30 10:46:44 beacon.go:180: [beacon] http(s) connection error send failed
2023/05/30 10:46:44 sliver.go:150: Beacon init error: send failed
2023/05/30 10:46:44 sliver.go:136: Reconnect sleep: 1m0s
```

**Desktop:**
 - OS: Kali 2023.1
 - Version
   ```
   [*] Client v1.5.39 - af46878f8520c0c65bbb1e80d813a9658ba09188 - linux/amd64
    Compiled at 2023-05-17 00:36:48 +0900 JST
    Compiled with go version go1.20.2 linux/amd64
   [*] Server v1.5.39 - af46878f8520c0c65bbb1e80d813a9658ba09188 - linux/amd64
    Compiled at 2023-05-17 00:36:47 +0900 JST
   ```

**Additional context**
I think it's because there is authentication implemented. But if I'd like to connect to a different sliver server, what configuration should I change? I checked the source code but couldn't find the needed information.

Thank you!

**Comment by moloch--** [comment] 2023-05-30 14:11
This is by design, the implant and server perform mutual authenticate over all protocols i.e., implants can only connect to the server that generated them. There is no option to disable this behavior, and we won't add an option to do so.

That said you can use [external builders](https://github.com/BishopFox/sliver/wiki/External-Builders) to leverage multiple servers, and you can also copy the server's "state" to a new server. By default, the server's state is stored in the `~/.sliver` directory. That is to say, you can copy this directory between servers and the implants will be interoperable (copy after generation).

**Comment by moloch--** [comment] 2023-05-30 14:19
The mutual authentication is [described here](https://github.com/BishopFox/sliver/wiki/Transport-Encryption)

**Closed** 2023-06-01 16:27 UTC
Labels: question
