### ISSUE TITLE
BOF execution instability

### ISSUE THREAD

**Issue by r00t0v3rr1d3** [BishopFox/sliver#679] opened 2022-05-18 14:45 UTC
**Describe the bug**
There is some instability in the BOF execution process. Many of the commonly used BOFs, even ones in the armory, don't appear to be working properly and can sometimes cause the entire implant to crash. For this issue bug report, I'll just list out a few TrustedSec SA BOFs from the armory that are unreliable. These tests were done on a Windows 10 21H2 x64 target machine and in both beacon and session mode. I am hopeful that most of these issues stem from a similar overarching fix for edge cases and aren't specific to these individual BOFs.

sa-netlocalgroup: kills the entire implant process every time
sa-netgroup: kills the entire implant process every time
sa-get-netsession: kills the entire implant process if you try to add a remote host
sa-ldapsearch: can't get an queries to work properly. Not sure if it is a parsing issue. Using known good queries from CS Beacon like "sa-ldapsearch objectclass=domain". Always get "The operating system cannot run %1."
sa-netshares: works locally - always throws an error 53 when attempting to use remotely. Tried IP, hostname, FQDN
sa-get-password-policy: works locally when given "" as argument. Always fails remotely with error 1722. Tried IP, hostname, FQDN

**Desktop (please complete the following information):**
 - OS: Latest Kali
 - Version:  v1.5.12

**Additional context** 
It is also plausible that I am not feeding in arguments properly - because some of these issues seem to revolve around not parsing the arguments. If you are able to get these modules to work by inputting arguments a specific way, I would appreciate seeing the examples. In my testing, the BOFs below seem to work consistently and as advertised:
sa-netstat
sa-ipconfig
sa-listdns
sa-cacls
sa-enum-local-sessions
sa-listmods

**Comment by moloch--** [comment] 2022-05-18 14:51
I think a couple of these need wstring instead of string but i've not had time to go back and test. Thanks for putting the list together we'll dig into the details asap.

**Comment by rkervella** [comment] 2022-05-18 20:25
I've seen some of these issues in the past, I'll try to give it a look.

**Comment by rkervella** [comment] 2022-05-19 20:33
Alright so I just had a quick look and most of the issue seem to be wrong argument types in the extension manifest:

- sa-netlocalgroup: `server` type should be `wstring` instead of `string`
- sa-netgroup: `domain` type should be `wstring` instead of `string`
- sa-get-netsession: `computer` type should be `wstring` instead of `string`
- sa-ldapsearch: this one I need to investigate more, arguments look correct
- sa-netshares: this one is missing an argument, which probably fucks up the parsing in the BOF code
- sa-get-password-policy:  `hostname` type should be `wstring` instead of `string`

**Comment by rkervella** [comment] 2022-05-20 00:32
@r00t0v3rr1d3 most of the issues should be fixed now.

**Comment by rkervella** [comment] 2022-05-20 00:52
For the `ldapsearch` BOF, did you get it to work on Cobalt Strike? I can't get it to work with TrustedSec's COFFLoader (which our own version is based on):

```shell
PS C:\Users\adminjdoe\Downloads> .\loader.exe go C:\users\adminjdoe\downloads\ldapsearch.x64.o 1400000010000000286f626a656374636c6173733d2a2900
...
        VirtualAddress: 0x277
        SymbolTableIndex: 0x2D
        Type: 0x4
        SymPtr: 0x19D
        SymVal: __imp_LoadLibraryA
        SectionNumber: 0x0
                Yep its an external symbol
                Library: LoadLibraryA
                Function: (null)
                Handle: 0x0
                ProcAddress: 0x0000000000000000
Failed to resolve symbol
Returning
Failed to run/parse the COFF file
```

**Comment by r00t0v3rr1d3** [comment] 2022-05-20 01:22
Yes, ldapsearch works great in Cobalt Strike. Your test range will need to be a box on a domain, but otherwise you could do a few of these queries that are simple and work in CS:

ldapsearch objectclass=domain
ldapsearch objectclass=computer
ldapsearch objectclass=group

**Comment by rkervella** [comment] 2022-05-20 01:28
Yeah my box is domain joined, the problem is during the parsing in the loader. When the BOF is compiled, some symbols are improperly tagged, which results in the loader not finding them. Looks like it's due to [this PR](https://github.com/trustedsec/CS-Situational-Awareness-BOF/issues/65). I need to dig more to see whether I should update the loader or the BOF itself.

**Comment by freefirex** [comment] 2022-05-20 14:09
Hello :)

This was brought to my attention and I did some testing, the issue appears to be with COFFLoader for ldapsearch specifically.  It's not mapping through some of the gimmy functions that BOF in CS auto link in (LoadLibraryA / GetProcAddress / FreeLibrary).

We'll fix that up on our end and I'll ping you in this issue when we have that fixed up so you can rebuild on your end.

Thanks again for all your work integrating this into your project, loving the work you're doing!

**Comment by rkervella** [comment] 2022-05-20 15:16
Wow that's great, thanks @freefirex . From what I've seen there's a couple of other BOFs that are probably affected (`nslookup`, `adcs_enum` ...) , so fixing the loader will make these work too I guess :)

**Comment by rkervella** [comment] 2022-05-23 07:24
@r00t0v3rr1d3 it should be fixed now. Just run `armory update` to get the new loader version and everything should work.

**Comment by r00t0v3rr1d3** [comment] 2022-05-23 10:42
Sounds great! I’ll check it all out and do more testing today. Thanks!

**Comment by r00t0v3rr1d3** [comment] 2022-05-23 17:58
After additional testing, I am seeing a huge improvement to stability and functionality! There are still some BOFs that are consistently killing the entire implant process though. sa-uptime, sa-netlocalgroup, sa-nslookup, sa-resources (I added that one myself). I mention sa-uptime first because that one takes no arguments and is consistently killing the implant process.

**Comment by freefirex** [comment] 2022-05-23 18:08
If its helpful from this end, I don't beleive those are issues in coffloader, x64 / x86 of that BOF (uptime) appear to run on our current codebase
<img width="449" alt="image" src="https://user-images.githubusercontent.com/3172440/169880563-25663ee6-3edb-43c6-93bb-6ee8352cc376.png">

**Comment by rkervella** [comment] 2022-05-24 08:37
Yeah I suspect something about a malformed extension manifest, I'll have a look.

**Comment by rkervella** [comment] 2022-05-24 08:51
@r00t0v3rr1d3 I can't reproduce the crash for `sa-uptime`, are you sure you're up to date? :

```shell
[server] sliver (EMPTY_JUDGMENT) > armory install sa-uptime

[*] Installing extension 'sa-uptime' (v0.0.14) ... done!

[server] sliver (EMPTY_JUDGMENT) > sa-uptime

[*] Successfully executed sa-uptime (coff-loader)
[*] Got output:
Uptime: 3 days, 1 hours, 18 minutes, 3 seconds
Boot time: 2022-05-21 00:26:54
```
Same thing for `sa-nslookup`:

```shell
[server] sliver (EMPTY_JUDGMENT) > help sa-nslookup

Makes a dns query. NOTE: Some situations are limited due to observed crashes

Usage:
======
  sa-nslookup [flags] hostname server type

Args:
=====
  hostname  string    Hostname to resolve
  server    string    DNS Server to use
  type      int       DNS record type (A, AAAA, or ANY), see https://docs.microsoft.com/en-us/windows/win32/dns/dns-constants for the actual values

Flags:
======
  -h, --help           display help
  -t, --timeout int    command timeout in seconds (default: 60)

[server] sliver (EMPTY_JUDGMENT) > sa-nslookup github.com 8.8.8.8
error: missing argument 'type'
[server] sliver (EMPTY_JUDGMENT) > sa-nslookup github.com 8.8.8.8 3

[*] Successfully executed sa-nslookup (coff-loader)
[*] Got output:
Query for domain name failed
No records found for given DNS query.


[server] sliver (EMPTY_JUDGMENT) > sa-nslookup github.com 8.8.8.8 2

[*] Successfully executed sa-nslookup (coff-loader)
[*] Got output:
NS github.com dns1.p08.nsone.net
NS github.com dns2.p08.nsone.net
NS github.com dns3.p08.nsone.net
NS github.com dns4.p08.nsone.net
NS github.com ns-1283.awsdns-32.org
NS github.com ns-1707.awsdns-21.co.uk
NS github.com ns-421.awsdns-52.com
NS github.com ns-520.awsdns-01.net


[server] sliver (EMPTY_JUDGMENT) > sa-nslookup github.com 8.8.8.8 1

[*] Successfully executed sa-nslookup (coff-loader)
[*] Got output:
A github.com 192.30.255.113
```

For the others:

- `sa-netlocalgroup` was missing an argument in the manifest, I'll push a fix
- `sa-resources`: if you can share your `extension.json` file, there's likely an issue in there

**Comment by r00t0v3rr1d3** [comment] 2022-05-24 13:36
Interesting. I’ll be taking another look at things today. I’ve been blowing everything away for the various “rounds” of testing we’ve been through on this effort - including the .sliver-client files. 

For the last round including the uptime issues - I used beacon mode with a 5 second callback time. I’ve also been consistently getting no output the first time any coffloader related extension is run. So after the initial beacon comes in, run something like sa-ipconfig. Get no output. Then run it again, and everything works after that. I’m also running these a few times, once per checkin to make sure it isn’t intermittently crashing.

**Comment by rkervella** [comment] 2022-05-24 13:55
Ah I only tested in session mode, there could be quirks in beacon mode indeed.

**Comment by rkervella** [comment] 2022-05-24 14:05
> I’ve also been consistently getting no output the first time any coffloader related extension is run. So after the initial beacon comes in, run something like sa-ipconfig. Get no output. Then run it again, and everything works after that.

That could be due to the way we do things in beacon mode. Under the hood, there are 3 RPC calls made to the implant:

- register the COFF loader extension
- register the BOF extension
- run the BOF extension

When an extension has been registered, there's only one RPC call made by the client to the implant, which could explain why the first time you get no output but it works fine the second time.

**Comment by r00t0v3rr1d3** [comment] 2022-05-24 15:33
Ok, I’m glad I dug into this! It is 100% something with beacon mode. uptime and resources both work in session mode fairly reliably. But in beacon mode they crash every time.

**Comment by rkervella** [comment] 2022-05-24 15:34
Neat I'll run some tests in beacon mode then.

**Comment by r00t0v3rr1d3** [comment] 2022-05-24 15:41
I’m definitely getting a few rpc errors for uptime and resources in session mode. Just up arrowing and hitting enter, a good half of the times plus I get “Call extension error: rpc error: code = Unknown desc = The parameter is incorrect.” It doesn’t kill the process in session mode though. Eventually it works on repeat attempts.

**Comment by rkervella** [comment] 2022-05-24 15:45
Weird for uptime as it doesn't take any parameters (resources shouldn't either, I just checked).

**Comment by r00t0v3rr1d3** [comment] 2022-05-24 15:52
Yeah. That’s why I wanted to focus on those. Since I wasn’t wondering if it was argument parsing related.

**Comment by r00t0v3rr1d3** [comment] 2022-11-09 18:42
Please re-open. This bug still very much exists, even in the latest version 1.5.31. http beacon implant. TrustedSec SA BOF resources or uptime BOF are a 100% crash guarantee. Neither take any arguments.

**Comment by r00t0v3rr1d3** [comment] 2022-11-09 19:52
Thanks! Sorry it took me so long to get around to testing it.

**Comment by rkervella** [comment] 2022-11-09 20:23
@r00t0v3rr1d3 can you provide details on your test case? Something like:
- target OS
- target arch
- generate command parameters

**Comment by r00t0v3rr1d3** [comment] 2022-11-09 20:27
Target OS: Windows 10 22H2
Target Arch: x64

sliver-server: 
http —disable-otp —persistent
generate beacon —http 192.168.1.250 —seconds 5 —jitter 5

On target:
run exe


On server:
use <beacon_guid>
sa-ipconfig (will come back blank because first BOF run always fails. Reported this previously)
sa-ifconfig (again, so you see BOFs are working)
sa-uptime

On target:
Implant process will die

**Comment by r00t0v3rr1d3** [comment] 2022-11-09 20:29
It’s also worth mentioning - because I think this came up in the past - but I’m using the vanilla - stock release binaries. Whatever debugging mode or other setup often used seems to baby things and prevent crashing.

**Comment by rkervella** [comment] 2022-11-09 20:43
Thanks I'll look into it.

**Comment by rkervella** [comment] 2022-11-10 00:24
Ok the good news is I managed to replicate in debug mode, and looks like it's a broader issue. Here's the stack trace (cc @moloch-- ):

```
...
2022/11/09 16:20:05 sliver.go:310: [beacon] task completed (id: 536101288308050523)
panic: sync: negative WaitGroup counter

goroutine 87 [running]:
sync.(*WaitGroup).Add(0xc000204010, 0xffffffffffffffff)
        /Users/lesnuages/.sliver/go/src/sync/waitgroup.go:83 +0x1ab
sync.(*WaitGroup).Done(0xc000204010)
        /Users/lesnuages/.sliver/go/src/sync/waitgroup.go:108 +0x25
main.beaconMain.func2({0xc0002044e0, 0x2, 0x2}, {0x0, 0x0})
        /Users/lesnuages/.sliver/slivers/windows/amd64/PALE_SPASM/src/github.com/bishopfox/sliver/sliver.go:316 +0x45a
github.com/bishopfox/sliver/implant/sliver/handlers.callExtensionHandler({0xc000179000, 0xe09, 0x1000}, 0xc000216150)
        /Users/lesnuages/.sliver/slivers/windows/amd64/PALE_SPASM/src/github.com/bishopfox/sliver/implant/sliver/handlers/handlers_windows.go:689 +0x5f8
created by main.beaconMain
        /Users/lesnuages/.sliver/slivers/windows/amd64/PALE_SPASM/src/github.com/bishopfox/sliver/sliver.go:302 +0xe4a
```

Looks like we somehow manage to get a negative WaitGroup counter by doing more `wg.Done()` than `wg.Add()`, I need to figure out why.

**Comment by r00t0v3rr1d3** [comment] 2022-11-10 00:57
Great news!

**Comment by moloch--** [comment] 2022-11-10 15:49
Interesting, I'll take a look

**Closed** 2023-03-29 16:47 UTC
Labels: bug
