### ISSUE TITLE
Issues installing sliver on arm

### ISSUE THREAD

**Issue by sinfulz** [BishopFox/sliver#668] opened 2022-04-27 12:37 UTC
I thought the last few commits to sliver allowed sliver to work on arm systems?

I am getting this error when installing sliver on arm:
```
┌──(root💀kali)-[/opt]
└─# curl https://sliver.sh/install|sudo bash                                                                                                                                                                    1 ⨯
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6038  100  6038    0     0   9516      0 --:--:-- --:--:-- --:--:--  9508
Running from /root
gpg: key 7DF912404449039C: "Sliver <sliver@bishopfox.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Downloading https://github.com/BishopFox/sliver/releases/download/v1.5.12/sliver-client_linux
Downloading https://github.com/BishopFox/sliver/releases/download/v1.5.12/sliver-client_linux.sig
Downloading https://github.com/BishopFox/sliver/releases/download/v1.5.12/sliver-server_linux
Downloading https://github.com/BishopFox/sliver/releases/download/v1.5.12/sliver-server_linux.sig
Verifying signatures ...
gpg: Signature made Thu 21 Apr 2022 06:11:52 AEST
gpg:                using RSA key 0ED3900D296CFA0283A4E4667DF912404449039C
gpg: Good signature from "Sliver <sliver@bishopfox.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0ED3 900D 296C FA02 83A4  E466 7DF9 1240 4449 039C
gpg: Signature made Thu 21 Apr 2022 06:11:52 AEST
gpg:                using RSA key 0ED3900D296CFA0283A4E4667DF912404449039C
gpg: Good signature from "Sliver <sliver@bishopfox.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0ED3 900D 296C FA02 83A4  E466 7DF9 1240 4449 039C
bash: line 126: /root/sliver-server: cannot execute binary file: Exec format error
```

Cheers

**Comment by moloch--** [comment] 2022-04-27 15:07
It's not supported by the install script yet, we're just laying the ground work for being able to compile Linux/ARM from source. We'll have a supported release in the future. Close as duplicate of #607

**Closed by moloch--** 2022-04-27 15:07 UTC
